### PR TITLE
Make required operator_dir slightly more explicit

### PR DESCRIPTION
**Pull request by nmars**
- Adjusted the language describing the operator metadata directory
- Other minor fixes suggested by my markdown linter

### CODE REVIEW

**Comment by nmars** [comment]
Please ignore the automated checks. They never should have run since this is a change to the single README.md. I will open an internal bug.

**Review by dirgim — APPROVED** [review]
LGTM

**Comment by jsztuka** [comment]
LGTM

**Review by jsztuka — COMMENTED** [review]
LGTM

**Review by jsztuka — APPROVED** [review]

**Pull request merged**
