### PR TITLE
Add the operator bundle data validation role using operator-sdk

### PR DESCRIPTION
**Pull request by dirgim**
* Add the validate-operator-bundle role to run on unpacked bundle data
* Add the role to the new local-test-operator-bundle playbook
* Add the validate-operator-bundle playbook for Jenkins pipeline usage

### CODE REVIEW

**Comment by nmars** [comment]
LGTM

**Comment by lslebodn** [comment]
LGTM but would be good to see results of test.  (@nmars  wink wink)

Therefore I have not approved changes yet in gh webui :-)

**Pull request merged**
